name: Docker

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '0 8 * 1/1 1'

jobs:
  release:
    name: CentOS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VERSION: [7, 8]
        VARIANT: ['', 'slim']
    env:
      DOCKERHUB_REPOSITORY: bromine0x23/centos
      GHCR_REPOSITORY: ${{ github.repository_owner }}/centos
      LATEST_VERSION: 8
      VERSION: ${{ matrix.VERSION }}
      VARIANT: ${{ matrix.VARIANT }}
    steps:
    - name: 检出代码
      uses: actions/checkout@v2
    - name: 设置 QEMU
      uses: docker/setup-qemu-action@v1
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: 登录 Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: 登录 GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: 设置变量
      id: variables
      run: |
        export VARIANT="${{ env.VARIANT }}"
        export LATEST_VERSION="${{ env.LATEST_VERSION }}"
        
        if [ "${VARIANT}" == "slim" ]; then
          export SUFFIX="-slim"
          echo "DOCKER_BUILD_ARG_IS_SLIM=slim" >> $GITHUB_ENV
        fi
        
        echo 'DOCKER_TAGS<<EOF' >> $GITHUB_ENV
        echo    "${{ env.DOCKERHUB_REPOSITORY }}:${{ env.VERSION }}${SUFFIX}" >> $GITHUB_ENV; echo ""
        echo "ghcr.io/${{ env.GHCR_REPOSITORY }}:${{ env.VERSION }}${SUFFIX}" >> $GITHUB_ENV; echo ""
        if [ "${LATEST_VERSION}" == "${{ env.VERSION }}"" ]; then
          echo    "${{ env.DOCKERHUB_REPOSITORY }}:latest${SUFFIX}" >> $GITHUB_ENV; echo ""
          echo "ghcr.io/${{ env.GHCR_REPOSITORY }}:latest${SUFFIX}" >> $GITHUB_ENV; echo ""
        fi
        echo 'EOF' >> $GITHUB_ENV
    - name: 构建及发布镜像
      uses: docker/build-push-action@v2
      with:
        context: ./${{ env.VERSION }}
        build-args:
          BASE_IMAGE=centos:${{ env.VERSION }}
          IS_SLIM=${{ env.IS_SLIM }}
        labels: |
          org.opencontainers.image.authors="Bromine0x23 <bromine0x23@gmail.com>"
          org.opencontainers.image.title="CentOS"
          org.opencontainers.image.version="${{ env.VERSION }}"
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.DOCKER_TAGS }}
