name: Docker

on:
  push:
    branches:
    - master

env:
  IMAGE_LABEL_AUTHORS: Bromine0x23 <bromine0x23@gmail.com>
  IMAGE_LABEL_TITLE: CentOS
  IMAGE_LABEL_DESCRIPTION: CentOS 基础镜像
  #DOCKER_REGISTRY: docker.pkg.github.com
  #DOCKER_USERNAME: ${{ github.actor }}
  #DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  #DOCKER_REPOSITORY: ${{ github.repository }}/centos
  DOCKER_REGISTRY: docker.io
  DOCKER_REPOSITORY: bromine0x23/centos

jobs:
  # See: https://github.com/docker/build-push-action
  release-centos7:
    name: CentOS 7
    runs-on: ubuntu-latest
    env:
      IMAGE_LABEL_VERSION: '7'
      DOCKER_TAGS: '7,latest'
      DOCKER_BUILD_CONTEXT: '7'
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 构建及发布镜像
        uses: docker/build-push-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          tags: ${{ env.DOCKER_TAGS }}
          path: ./${{ env.DOCKER_BUILD_CONTEXT }}
          labels: org.opencontainers.image.authors="${{ env.IMAGE_LABEL_AUTHORS }}",org.opencontainers.image.title="${{ env.IMAGE_LABEL_TITLE }}",org.opencontainers.image.description="${{ env.IMAGE_LABEL_DESCRIPTION }}",org.opencontainers.image.version="${{ env.IMAGE_LABEL_VERSION }}"
          add_git_labels: true
  release-centos7-slim:
    name: CentOS 7 (Slim version)
    runs-on: ubuntu-latest
    env:
      IMAGE_LABEL_VERSION: '7'
      DOCKER_TAGS: '7-slim,latest-slim'
      DOCKER_BUILD_CONTEXT: '7-slim'
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 构建及发布镜像
        uses: docker/build-push-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          tags: ${{ env.DOCKER_TAGS }}
          path: ./${{ env.DOCKER_BUILD_CONTEXT }}
          labels: org.opencontainers.image.authors="${{ env.IMAGE_LABEL_AUTHORS }}",org.opencontainers.image.title="${{ env.IMAGE_LABEL_TITLE }}",org.opencontainers.image.description="${{ env.IMAGE_LABEL_DESCRIPTION }}",org.opencontainers.image.version="${{ env.IMAGE_LABEL_VERSION }}"
          add_git_labels: true
  release-centos8:
    name: CentOS 8
    runs-on: ubuntu-latest
    env:
      IMAGE_LABEL_VERSION: '8'
      DOCKER_TAGS: '8'
      DOCKER_BUILD_CONTEXT: '8'
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 构建及发布镜像
        uses: docker/build-push-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          tags: ${{ env.DOCKER_TAGS }}
          path: ./${{ env.DOCKER_BUILD_CONTEXT }}
          labels: org.opencontainers.image.authors="${{ env.IMAGE_LABEL_AUTHORS }}",org.opencontainers.image.title="${{ env.IMAGE_LABEL_TITLE }}",org.opencontainers.image.description="${{ env.IMAGE_LABEL_DESCRIPTION }}",org.opencontainers.image.version="${{ env.IMAGE_LABEL_VERSION }}"
          add_git_labels: true
  release-centos8-slim:
    name: CentOS 8 (Slim version)
    runs-on: ubuntu-latest
    env:
      IMAGE_LABEL_VERSION: '8'
      DOCKER_TAGS: '8-slim'
      DOCKER_BUILD_CONTEXT: '8-slim'
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 构建及发布镜像
        uses: docker/build-push-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          tags: ${{ env.DOCKER_TAGS }}
          path: ./${{ env.DOCKER_BUILD_CONTEXT }}
          labels: org.opencontainers.image.authors="${{ env.IMAGE_LABEL_AUTHORS }}",org.opencontainers.image.title="${{ env.IMAGE_LABEL_TITLE }}",org.opencontainers.image.description="${{ env.IMAGE_LABEL_DESCRIPTION }}",org.opencontainers.image.version="${{ env.IMAGE_LABEL_VERSION }}"
          add_git_labels: true