name: 镜像构建

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '0 0 1 * *'

env:
  IMAGE_AUTHORS: Bromine0x23 <bromine0x23@gmail.com>
  IMAGE_PLATFORMS: linux/amd64,linux/arm64

jobs:
  template:
    name: CentOS
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
    - &checkout
      name: 检出代码
      id: checkout
      uses: actions/checkout@v2
    - &setup_qemu
      name: 设置 QEMU
      id: setup_qemu
      uses: docker/setup-qemu-action@v1
    - &setup_buildx
      name: 设置 Docker Buildx
      id: setup_buildx
      uses: docker/setup-buildx-action@v1
    - &login_dockerhub
      name: 登录 Docker Hub
      id: login_dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - &login_ghcr
      name: 登录 GitHub Container Registry
      id: login_ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - &build_push
      name: 构建及发布镜像
      id: build_push
      uses: docker/build-push-action@v2
      with:
        context: ./${{ env.IMAGE_CONTEXT }}
        build-args: ${{ env.IMAGE_BUILD_ARGS }}
        labels: |
          org.opencontainers.image.authors="${{ env.IMAGE_AUTHORS }}"
          org.opencontainers.image.title="${{   env.IMAGE_TITLE   }}"
          org.opencontainers.image.version="${{ env.IMAGE_VERSION }}"
        platforms: ${{ env.IMAGE_PLATFORMS }}
        push: true
        tags: ${{ env.IMAGE_TAGS }}
    - &trivy
      name: 漏洞扫描
      id: trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.IMAGE_REPOSITORY_DOCKERHUB }}:${{ env.IMAGE_TAG }}'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        format: 'table'

  centos:
    name: CentOS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CENTOS_VERSION: [7, 8]
        IMAGE_VARIANT: ['', 'slim']
    env:
      CENTOS_VERSION_LATEST: 8
      IMAGE_REPOSITORY_DOCKERHUB: bromine0x23/centos
      IMAGE_REPOSITORY_GHCR: ghcr.io/${{ github.repository_owner }}/centos
      IMAGE_TITLE: CentOS
      IMAGE_VERSION: ${{ matrix.CENTOS_VERSION }}
      IMAGE_VARIANT: ${{ matrix.IMAGE_VARIANT }}
    steps:
    - name: 设置
      id: setup
      run: |
        export IMAGE_VERSION="${{ env.IMAGE_VERSION }}"
        export IMAGE_VARIANT="${{ env.IMAGE_VARIANT }}"
        export CENTOS_VERSION_LATEST="${{ env.CENTOS_VERSION_LATEST }}"
        
        echo "IMAGE_CONTEXT=${{ env.IMAGE_VERSION }}"        >> $GITHUB_ENV
        
        echo "IMAGE_BUILD_ARGS<<EOF"        >> $GITHUB_ENV
        echo "BASE_IMAGE=centos:${{ env.IMAGE_VERSION }}" >> $GITHUB_ENV; echo ""
        if [ "${IMAGE_VARIANT}" == "slim" ]; then
          echo "IS_SLIM=slim" >> $GITHUB_ENV; echo ""
        else
          echo "IS_SLIM="     >> $GITHUB_ENV; echo ""
        fi
        echo 'EOF' >> $GITHUB_ENV
        
        export IMAGE_TAG="${{ env.IMAGE_VERSION }}${IMAGE_VARIANT:+-${IMAGE_VARIANT}}"
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "IMAGE_TAGS<<EOF"        >> $GITHUB_ENV
        echo "${{ env.IMAGE_REPOSITORY_DOCKERHUB }}:${IMAGE_TAG}" >> $GITHUB_ENV; echo ""
        echo "${{ env.IMAGE_REPOSITORY_GHCR      }}:${IMAGE_TAG}" >> $GITHUB_ENV; echo ""
        if [ "${IMAGE_VERSION}" == "${CENTOS_VERSION_LATEST}" ]; then
          export IMAGE_TAG_LATEST="${IMAGE_VARIANT:-latest}"
          echo "${{ env.IMAGE_REPOSITORY_DOCKERHUB }}:${IMAGE_TAG_LATEST}" >> $GITHUB_ENV; echo ""
          echo "${{ env.IMAGE_REPOSITORY_GHCR      }}:${IMAGE_TAG_LATEST}" >> $GITHUB_ENV; echo ""
        fi
        echo 'EOF' >> $GITHUB_ENV
    - *checkout
    - *setup_qemu
    - *setup_buildx
    - *login_dockerhub
    - *login_ghcr
    - *build_push
    - *trivy