name: Docker

on:
  push:
    branches:
    - master
  schedule:
  - cron:  '0 8 * 1/1 1'

env:
  AUTHORS: Bromine0x23 <bromine0x23@gmail.com>
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  release:
    name: CentOS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VERSION: [7, 8]
        VARIANT: ['', 'slim']
    env:
      DOCKERHUB_REPOSITORY: bromine0x23/centos
      GHCR_REPOSITORY: ${{ github.repository_owner }}/centos
      LATEST_VERSION: 8
      VERSION: ${{ matrix.VERSION }}
      VARIANT: ${{ matrix.VARIANT }}
      TITLE: CentOS
    steps:
    - name: 检出代码
      uses: actions/checkout@v2
    - name: 设置 QEMU
      uses: docker/setup-qemu-action@v1
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: 登录 Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: 登录 GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: 设置变量
      id: variables
      run: |
        export VERSION="${{ env.VERSION }}"
        export VARIANT="${{ env.VARIANT }}"
        export LATEST_VERSION="${{ env.LATEST_VERSION }}"
        
        echo 'DOCKER_TAGS<<EOF' >> $GITHUB_ENV
        echo    "${{ env.DOCKERHUB_REPOSITORY }}:${{ env.VERSION }}${VARIANT:+-${VARIANT}}" >> $GITHUB_ENV; echo ""
        echo "ghcr.io/${{ env.GHCR_REPOSITORY }}:${{ env.VERSION }}${VARIANT:+-${VARIANT}}" >> $GITHUB_ENV; echo ""
        if [ "${VERSION}" == "${LATEST_VERSION}" ]; then
          echo    "${{ env.DOCKERHUB_REPOSITORY }}:${VARIANT:-latest}" >> $GITHUB_ENV; echo ""
          echo "ghcr.io/${{ env.GHCR_REPOSITORY }}:${VARIANT:-latest}" >> $GITHUB_ENV; echo ""
        fi
        echo 'EOF' >> $GITHUB_ENV
        
        echo "DOCKER_BUILD_ARG_BASE_IMAGE=centos:${{ env.VERSION }}" >> $GITHUB_ENV
        if [ "${VARIANT}" == "slim" ]; then
          echo "DOCKER_BUILD_ARG_IS_SLIM=slim" >> $GITHUB_ENV
        fi
    - name: 构建及发布镜像
      uses: docker/build-push-action@v2
      with:
        context: ./${{ env.VERSION }}
        build-args: |
          BASE_IMAGE=centos:${{ env.DOCKER_BUILD_ARG_BASE_IMAGE }}
          IS_SLIM=${{ env.DOCKER_BUILD_ARG_IS_SLIM }}
        labels: |
          org.opencontainers.image.authors="${{ env.AUTHORS }}"
          org.opencontainers.image.title="${{ env.TITLE }}"
          org.opencontainers.image.version="${{ env.VERSION }}"
        platforms: ${{ env.PLATFORMS }}
        push: true
        tags: ${{ env.DOCKER_TAGS }}
